init

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -8,8 +8,8 @@ fi
 
 # If running the rails server then create or migrate existing database
 if echo "$*" | grep -q "rails.*server"; then
-  ./bin/rails db:prepare
+  ./bin/rails db:prepare || echo "db:prepare failed, continuing..."
   ./bin/rails db:seed 2>/dev/null || true
 fi
 
-exec "${@}"
+exec "$@"
